# https://github.com/docker/compose/releases
# https://docs.docker.com/compose/compose-file/
# Use root/example as user/password credentials
version: '3.1'

# https://stackoverflow.com/questions/41334488/error-in-file-docker-compose-yml-volume-must-be-a-mapping-not-a-string
# In Windows System, Docker Desktop should add current project directory to "Fire Sharing", else directory mounting will fail
volumes:
  data-dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/mysql-data-dir
  code-dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD/..

networks:
  lnmp-net:
    driver: bridge

services:

  nginx:
    container_name: nginx
    image: nginx:1.16.1
    ports:
      # external port: internal port
      - 9977:80
    privileged: true
    volumes:
      - $PWD/nginx-conf-dir/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx-conf-dir/conf.d:/etc/nginx/conf.d
      - $PWD/nginx-conf-dir/logs:/var/log/nginx
      - code-dir:/usr/share/nginx/html/mybook
    depends_on:
      - db
      - php
    restart: always
    networks:
      - lnmp-net

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    # external port: internal port
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - data-dir:/var/lib/mysql
    networks:
      - lnmp-net

  php:
    container_name: php
    image: php-dev
    build:
      context: .
      args:
        - proxy=http://proxy.maoer.co:8123
      dockerfile: Dockerfile-php
    privileged: true
    volumes:
      - $PWD/php-conf-dir/logs:/usr/local/var/log
      - $PWD/php-conf-dir/php.ini:/usr/local/etc/php/php.ini
      - $PWD/php-conf-dir/www.conf:/usr/local/etc/php-fpm.d/www.conf # max_children
      - code-dir:/usr/share/nginx/html/mybook
    #entrypoint: /entrypoint.sh
    restart: always
    networks:
      - lnmp-net

  dbui:
    image: adminer  # web ui for MySQL
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - lnmp-net
